---
all:
  children:
    bastion:
      hosts:
        bastion:
          ansible_host: "{{ bastion_public_ip }}"
          ansible_user: opc
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
    private_instances:
      hosts:
        private_instance:
          ansible_host: "{{ private_instance_private_ip }}"
          ansible_user: opc
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
          ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -i {{ ssh_private_key_path }} opc@{{ bastion_public_ip }}'"
        private_instance_secondary:
          ansible_host: "{{ second_private_instance_private_ip }}"
          ansible_user: opc
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
          ansible_ssh_common_args: "-o ProxyCommand='ssh -W %h:%p -i {{ ssh_private_key_path }} opc@{{ bastion_public_ip }}'"
          when_condition: "{{ create_second_instance | bool }}"