---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install common packages
  dnf:
    name:
      - wget
      - unzip
      - curl
      - vim
      - net-tools
      - firewalld
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Set timezone
  timezone:
    name: UTC